inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  # - rubocop-rspec_rails # throws errors if included

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'